# Generated by Django 5.1.7 on 2025-03-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUpForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineUp_Date', models.CharField(default='', max_length=20)),
                ('Port', models.CharField(default='', max_length=20)),
                ('Berth', models.CharField(default='', max_length=20)),
                ('IMO_No', models.CharField(default='', max_length=20)),
                ('Slt', models.CharField(default='', max_length=20)),
                ('Vessel', models.CharField(default='', max_length=20)),
                ('LOA', models.IntegerField(default='', max_length=20)),
                ('Beam', models.IntegerField(default='', max_length=20)),
                ('Draft', models.IntegerField(default='', max_length=20)),
                ('ETA_ATA_Date', models.CharField(blank=True, max_length=20, null=True)),
                ('ETA_ATA_Time', models.CharField(blank=True, max_length=20, null=True)),
                ('ETB_ATB_Date', models.CharField(blank=True, max_length=20, null=True)),
                ('ETB_ATB_Time', models.CharField(blank=True, max_length=20, null=True)),
                ('ETD_ATD_Date', models.CharField(blank=True, max_length=20, null=True)),
                ('ETD_ATD_Time', models.CharField(blank=True, max_length=20, null=True)),
                ('Cargo1', models.CharField(default='', max_length=20)),
                ('CargoQty1', models.IntegerField(default='', max_length=20)),
                ('CargoUnits1', models.CharField(default='', max_length=20)),
                ('Cargo2', models.CharField(default='', max_length=20)),
                ('CargoQty2', models.IntegerField(default=0)),
                ('CargoUnits2', models.CharField(default='', max_length=20)),
                ('Cargo3', models.CharField(default='', max_length=20)),
                ('CargoQty3', models.IntegerField(default=0)),
                ('CargoUnits3', models.CharField(default='', max_length=20)),
                ('VesselType', models.CharField(default='', max_length=20)),
                ('Operations', models.CharField(default='', max_length=20)),
                ('Shipper', models.CharField(default='', max_length=20)),
                ('Receiver', models.CharField(default='', max_length=20)),
                ('Principal', models.CharField(default='', max_length=20)),
                ('Owner', models.CharField(default='', max_length=20)),
                ('C_F', models.CharField(default='', max_length=20)),
                ('LastPort', models.CharField(default='', max_length=20)),
                ('NextPort', models.CharField(default='', max_length=20)),
                ('LoadPort', models.CharField(default='', max_length=20)),
                ('DischargePort', models.CharField(default='', max_length=20)),
                ('ChartererAgent', models.CharField(default='', max_length=20)),
                ('OwnersAgent', models.CharField(default='', max_length=20)),
                ('CurrentStatus', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Port_Berth_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(default='', max_length=20)),
                ('Port', models.CharField(default='', max_length=20)),
                ('Berth', models.CharField(default='', max_length=20)),
                ('Berth_Type', models.CharField(default='', max_length=20)),
                ('Cargos_Handled_on_Berth', models.CharField(default='', max_length=200)),
                ('Terminal', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
