# Generated by Django 5.1.7 on 2025-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_lineupform_port_berth_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineupform',
            name='ETA_ATA_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineupform',
            name='ETA_ATA_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineupform',
            name='ETB_ATB_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineupform',
            name='ETB_ATB_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineupform',
            name='ETD_ATD_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineupform',
            name='ETD_ATD_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
