# Generated by Django 5.1.7 on 2025-03-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_lineupform_eta_ata_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupform',
            name='Remarks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
